### ISSUE TITLE
Issue with Python client3.py

### ISSUE THREAD

**Issue by remiljw** [insidesherpa/JPMC-tech-task-1-PY3#10]
![issue](https://user-images.githubusercontent.com/39375446/69198232-51fd9680-0b34-11ea-8193-1116a169fb07.png)
Python client3.py throws up error as shown

**Comment by remiljw** [comment]
I am setting up on Windows 10 with Python 3.5

**Comment by remiljw** [comment]
issue fixed. 
added `.decode('utf-8'))`

**Comment by jbf-insidesherpa** [comment]
@remiljw glad it works on your end. However it should be working out of the box for python3 even without that change you did (tested on Windows too  | python3.7.4.). I'll close this issue now but I'm curious what is your python3 version?

**Comment by remiljw** [comment]
Python 3.5.2

Michael Ajanaku

**Comment by jbf-insidesherpa** [comment]
Ah just verified. It does happen on 3.5.2. We'll update the slides so people don't encounter the same issue. Thanks

**Comment by VishnuVuggepalli** [comment]
![JPMCCommand Prompt](https://user-images.githubusercontent.com/55404692/91631022-d2babe80-e9f3-11ea-9149-285176ee623a.png)
I get these errors what should i do ??
