### ISSUE TITLE
client3.py NameError: name 'prices' is not defined 

### ISSUE THREAD

**Issue by sagarpassi** [insidesherpa/JPMC-tech-task-1-PY3#11]
![name error](https://user-images.githubusercontent.com/57231851/69965472-4040c980-150c-11ea-843e-7ba332f458aa.PNG)

when trying to print i get a name error 

print ("Ratio %s" %(getRatio(prices['ABC'],prices['DEF'])))

**Comment by jbf-insidesherpa** [comment]
@sagarpassi seems like you have a similar problem that's being discussed here: https://github.com/insidesherpa/JPMC-tech-task-1/issues/28.

You're just missing some code you didn't properly copy/follow from the guide (i.e. you must have a `prices` variable and insert values into it in the second / inner for loop in the main method) Please re-read the making changes guide again.
