### ISSUE TITLE
urlopen error [WinError 10061]

### ISSUE THREAD

**Issue by amin-farjadi** [insidesherpa/JPMC-tech-task-1-PY3#12]
Hi, when I try to run the client3.py script from the cmd line (as admin), I get the error:
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

**Comment by jbf-insidesherpa** [comment]
@amin-farjadi have you made sure that you're also running the server script alongside the client?

**Comment by jbf-insidesherpa** [comment]
Closing this as it's been quite some time. Feel free to reopen if it's still relevant @amin-farjadi
