### ISSUE TITLE
Cannot start client.py

### ISSUE THREAD

**Issue by damiecode** [insidesherpa/JPMC-tech-task-1-PY3#13]
I cannot start the client3.py
![Screenshot from 2019-12-17 09-07-55](https://user-images.githubusercontent.com/29799224/70976758-cdf3eb80-20ac-11ea-9ce2-5913fabbe272.png)

**Comment by jbf-insidesherpa** [comment]
@damiecode what's your python version? Also what's the output of 
**python --version** and **python3 --version**

**Comment by jbf-insidesherpa** [comment]
Closing this now as it's been quite some time. @damiecode please feel free to reopen if it's still relevant
