### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by shubhamkumar906** [insidesherpa/JPMC-tech-task-1-PY3#130]
Traceback (most recent call last):
  File "client3.py", line 60, in <module>
    print ("Ratio %s" % (getRatio(prices['ABC'], prices['DEF'])))
KeyError: 'ABC'
[image](https://user-images.githubusercontent.com/60883994/84098594-4668b300-aa25-11ea-85ce-744a81fe198c.png)

![Screenshot (55)](https://user-images.githubusercontent.com/60883994/84098665-7a43d880-aa25-11ea-987b-2afe7de290c9.png)

**Comment by shubhamkumar906** [comment]
please help me out

**Comment by goku9313** [comment]
How are you able to run client.py and server.py file
When I am running server.py it shows me below message  and nothing on screen
HTTP server started on port 8080
if I run client.py I got lots of error 
Help if You could
