### ISSUE TITLE
Ratio1 is repeatedly printing

### ISSUE THREAD

**Issue by bshan7** [insidesherpa/JPMC-tech-task-1-PY3#139]
![2020-06-17](https://user-images.githubusercontent.com/58856227/84917995-b0e0b980-b0dd-11ea-9153-ab1302a8283e.png)

i ran python client3.py and i am geting this printing repeatedly in the cmd. Is there any adversity?

**Comment by bshan7** [comment]
Oops! This was posted as I finished the first step and didnt know what output I will get. After reading further I got clarified.

**Comment by madiha-dev** [comment]
@bshan7 how u resolve it?
