### ISSUE TITLE
 'float' object is not subscriptable

### ISSUE THREAD

**Issue by 1030488** [insidesherpa/JPMC-tech-task-1-PY3#14]
Dear Supervisor，
  
when I execute the patch file ’python client3. py‘  which has been modified in accordance with the guide，it shows that Type Error :'float' object is not subscript-able at line 46. The Type Error is in the module "print ("Ratio %s" % getRatio(price['DEF'], price['ABC']))".
![image](https://user-images.githubusercontent.com/58537814/71441925-976a4080-273e-11ea-8246-92025301798a.png)
![image](https://user-images.githubusercontent.com/58537814/71441973-cbddfc80-273e-11ea-9e1c-e8fef6db983c.png)
 
Thank you for your kind help.

Best Regards,
RD

**Comment by jbf-insidesherpa** [comment]
![image](https://user-images.githubusercontent.com/54832297/71555150-95b4bb80-2a63-11ea-8ff8-b5e51b406e47.png)

@1030488 you made a mistake when referring to `prices['DEF']` as just `price['DEF']. Same with `prices['ABC']
