### ISSUE TITLE
ModuleNotFoundError: No module named 'dateutil'

### ISSUE THREAD

**Issue by iv4nd** [insidesherpa/JPMC-tech-task-1-PY3#16]
I have installed this package using python3 successfully. After trying to run the server on python3 again, I'm still getting error that states "No module named 'dateutil'"

**Comment by jbf-insidesherpa** [comment]
@iv4nd your pip command probably doesn't match the python3 version you have. i.e. when you did **pip install python-dateutil** you probably install date-util for a different python version on your pc. You can verify if your pip command's version matches your python3 version by doing **pip --version**. If it matches **python3 --version** then it should be good but my guess is it's not. The pip that matches your **python3** version in your system most probably resides in the Scripts folder where your python3 executable/binary is located.
