### ISSUE TITLE
Stuck at "HTTP server started on port 8080"

### ISSUE THREAD

**Issue by JunaidVM98** [insidesherpa/JPMC-tech-task-1-PY3#165]
After running "python server3.py", I get the "HTTP server started on port 8080" message and then nothing happens. I don't get the "Query received ..." message that the tutorial shows.

![python](https://user-images.githubusercontent.com/69819758/90440334-f6fecd00-e0ce-11ea-80a5-61ee68caa029.PNG)

I even tried changing the port to 8085 but that didn't help. It's not an issue with the firewall as I gave access when the prompt showed up, and even tried again after disabling the firewall altogether,

Any help is appreciated!

**Comment by YH-Sui** [comment]
This happened to me as well

**Comment by ostevermer** [comment]
I'm having the same issue. This issue has been brought up quite a few times, but none of the previously posted solutions worked for me.

**Comment by banty306** [comment]
**Attention Please!**
Once you start the server and it shows as "HTTP server started on port 8080" then your server is running perfectly. Now you need to run the client.py / client3.py on the other CMD. Then you will get the queries received messages on the server panel. Try it!

**Comment by JunaidVM98** [comment]
Apologies for the late response, but what @banty306 suggested worked.
