### ISSUE TITLE
Server not running/ client:HTTP Error

### ISSUE THREAD

**Issue by Rinju99** [insidesherpa/JPMC-tech-task-1-PY3#17]
I am using python3 and it's not working don't know why...server just stuck there

![jpm_error1](https://user-images.githubusercontent.com/47399602/76275047-49021380-6250-11ea-90a8-c2403bfc0351.png)

**Comment by jbf-insidesherpa** [comment]
@Rinju99 that's fine (it's also stated in the guide that that is ok). The server is meant to just listen for requests from the client on port 8080 so it might look stuck but it's not.
