### ISSUE TITLE
Wrong data value in client_test.py

### ISSUE THREAD

**Issue by maramsumanth** [insidesherpa/JPMC-tech-task-1-PY3#18]
In the **test_getDataPoint_calculatePriceBidGreaterThanAsk** method of client_test.py, for the second quote, bid_price=117.87 and ask_price=121.68, but according to the method bid_price should be > ask_price, here reverse is happening.

**Comment by jbf-insidesherpa** [comment]
@maramsumanth apologies for getting back to this only now, I'm not sure I'm getting your question correctly. Can you point out in a screenshot what exactly it is that you don't understand?

**Comment by maramsumanth** [comment]
The name of the method **test_getDataPoint_calculatePriceBidGreaterThanAsk** indicates that the stock should have **bid_price > ask_price**, but the data has values of bid_price and ask_price such that bid_price < ask_price, which is incorrect.

**Comment by jbf-insidesherpa** [comment]
@maramsumanth oh I see what you mean. Feel free to change the test data being used. You have more freedom/control as to what test cases you wish to run in the client_test.py file
