### ISSUE TITLE
InsideSherpa>JPMC-tech-task-1py3 on Windows 10

### ISSUE THREAD

**Issue by srgarcess** [insidesherpa/JPMC-tech-task-1-PY3#2]
I am trying to install the dependencies for Windows  10, and I have accomplished the following task successfully  assuming that the Command Prompt is running as an Administrator:

- git clone https://github.com/insidesherpa/JPMC-tech-task-1-py3.git
- python --version is Python 3.4.0
- python3 get-pip.py
- To install the dateutil I had to do:  **python -m pip install python-dateutil**
![image](https://user-images.githubusercontent.com/56943455/67963953-72899f00-fbcd-11e9-8146-61c16922e0fc.png)
- Then running the server as: **python server3.py**
![image](https://user-images.githubusercontent.com/56943455/67964256-f5125e80-fbcd-11e9-8460-c51233fa89e8.png)

- Then the error comes when I ran the client as an administrator: python client3.py
![image](https://user-images.githubusercontent.com/56943455/67964629-93062900-fbce-11e9-8404-011d450a2f48.png)

- I ran the client_test.py: 
![image](https://user-images.githubusercontent.com/56943455/67965502-22f8a280-fbd0-11e9-97ed-49a8c42e0696.png)

Looks like I'm connected to the server because it is receiving queries, but I'm not sure If I'm done with the whole process, Can anyone help me please?

**Comment by jbf-insidesherpa** [comment]
@srgarcess https://www.python.org/downloads/release/python-380/

**Comment by jbf-insidesherpa** [comment]
@srgarcess I presume all issues are fixed on your end now. I'll close this issue. Please feel free to reopen or create a new one should you encounter other problems
