### ISSUE TITLE
Python not found

### ISSUE THREAD

**Issue by soye001** [insidesherpa/JPMC-tech-task-1-PY3#204]
Comes up with python not found run without arguments to install from the Microsoft Store,
I also ran the test suggestion using note pad and it works, so not too sure what the error is.

**Comment by The-Real-Thisas** [comment]
The question is already answered in #203 . I would suggest closing this issue to avoid duplicate questions.

**Comment by soye001** [comment]
yes of course thank you

**Comment by The-Real-Thisas** [comment]
Glad to help.
