### ISSUE TITLE
C:\Users\DELL\JPMC-tech-task-1-py3>python server.py python: can't open file 'C:\\Users\\DELL\\JPMC-tech-task-1-py3\\server.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dewan2002** [insidesherpa/JPMC-tech-task-1-PY3#236]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/80190765/171992273-a3b9b0f0-abac-41e1-b591-7ac2ba660573.png">

**Comment by vaishnavisamboji** [comment]
How did you solve this issue ?
