### ISSUE TITLE
NameError: Prices is not defined

### ISSUE THREAD

**Issue by brianw921** [insidesherpa/JPMC-tech-task-1-PY3#26]
I followed the instructions precisely and I got a name error that prices is not defined

```Traceback (most recent call last):
  File "client3.py", line 60, in <module>
    print ("Ratio %s" % (getRatio(prices['ABC'], prices['DEF'])))
NameError: name 'prices' is not defined```

**Comment by joekariuki** [comment]
Hi @brianw921,

Have you tried defining the 'prices' object in the price query section at the bottom of the file? You should have something along the lines of `prices = {}` before the 'quotes' for loop. Hopefully this should fix the issue you are having :)

**Comment by brianw921** [comment]
I did not catch that Thank you!
