### ISSUE TITLE
Facing an error while executing git commit -m 'Create Patch File'

### ISSUE THREAD

**Issue by AnimeshMaheshwari22** [insidesherpa/JPMC-tech-task-1-PY3#30]
error: pathspec 'Patch' did not match any file(s) known to git.
error: pathspec 'File'' did not match any file(s) known to git.

**Comment by Avinash-1501** [comment]
I'm facing the same problem

**Comment by Avinash-1501** [comment]
@AnimeshMaheshwari22 
type ``` git commit -m "Create Patch File" ``` instead of ```git commit -m 'Create Patch File' ```
use double quotes instead of single quote

**Comment by AnimeshMaheshwari22** [comment]
That solved the issue. Thanks!
