### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by Aakash2408** [insidesherpa/JPMC-tech-task-1-PY3#44]
After moving to  Desktop\JPMC-tech-task-1-py3>   when I use python3 server3.py nothing happens it just move to the next line which is same as of the previous    Desktop\JPMC-tech-task-1-py3>
.Now what to do am stuck?

**Comment by Aakash2408** [comment]
![python error](https://user-images.githubusercontent.com/47134609/80968105-08c8a700-8e35-11ea-89b4-5c9b59672ac4.png)

**Comment by harshrey** [comment]
Did you find a solution? I have the same error

**Comment by Pavan-249** [comment]
use python server3.py instead
