### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by prakhargvp** [insidesherpa/JPMC-tech-task-1-PY3#48]
`$ python3 client3.py `

![Screenshot from 2020-05-05 07-53-32](https://user-images.githubusercontent.com/7056772/81030215-a0fe7480-8ea5-11ea-8cc1-76f89369c6f7.png)

**Comment by Vraajj** [comment]
Same issue

**Comment by vikashkumr** [comment]
decode it, add ".decode('utf-8')"  just after read()
quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read().decode('utf-8'))

**Comment by Raghuwendr** [comment]
same error

**Comment by prakhargvp** [comment]
Go to client3.py and 

Update

![image](https://user-images.githubusercontent.com/7056772/82110227-20b7f900-975a-11ea-94ae-ce20c736653c.png)

To 
![image](https://user-images.githubusercontent.com/7056772/82110169-be5ef880-9759-11ea-8ec8-f1cb3b979111.png)

```
quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read().decode('utf-8'))
```
