### ISSUE TITLE
problem in patching in cmd .

### ISSUE THREAD

**Issue by saisriteja** [insidesherpa/JPMC-tech-task-1-PY3#49]
JPMC-tech-task-1-py3>git commit -m 'Create Patch File"
error: pathspec 'Patch' did not match any file(s) known to git
error: pathspec 'File' did not match any file(s) known to git

**Comment by AbhineelBeohar** [comment]
Did you find a solution to this?

**Comment by shreeya59** [comment]
I'm having the same issue. Please help

**Comment by saisriteja** [comment]
i just changed the name
'create patch file' to 'first commit'
it worked for me.

**Comment by shreeya59** [comment]
Hey @saisriteja 
I tried 'first commit' instead but it's giving me the same error for 'commit'.
Can't fix it

Thanks for reaching out   :)

**Comment by saisriteja** [comment]
here is what I have done
git add . initially instead od git add _A 
and rest remaining
try it

**Comment by shreeya59** [comment]
Oh that worked.
Thank you so much @saisriteja !

**Comment by saisriteja** [comment]
Welcome
