### ISSUE TITLE
Issues with python server3.py

### ISSUE THREAD

**Issue by mphobwcodes** [insidesherpa/JPMC-tech-task-1-PY3#5]
I installed python 3, and was able to run all the commands signed in as an administrator. I also was able to successfully install pip and its dependencies because when running the python server command i was getting the dateutil error. I followed how to install pip, and now i see what version I have but when I run the server3 command i get the below error
![image](https://user-images.githubusercontent.com/36450959/68421540-78065c80-016c-11ea-95e2-abb6a166f25e.png)

**Comment by jbf-insidesherpa** [comment]
@mphobwcodes there's probably something running on port8080 on your machine. You need to free it up. 

To do this, can you try:
1. Execute `netstat -ano` on your machine
2. Look for the process using up port 8080 . 
![image](https://user-images.githubusercontent.com/54832297/68444369-970afa00-0211-11ea-977b-71f49dfd4a12.png)

3. Try to stop/kill that process on your machine and try to restart the server application after. Here's a guide on how to do that: https://community.talend.com/t5/Architecture-Best-Practices-and/How-to-find-and-kill-a-process-running-on-a-port/ta-p/55315

**Comment by mphobwcodes** [comment]
Thanks. That resolved the issue.

**Comment by onosdev** [comment]
![image](https://user-images.githubusercontent.com/89713954/132948687-ced55d87-d191-45eb-8950-177818601293.png)
please help with the solution with this error
