### ISSUE TITLE
python3 server.py 

### ISSUE THREAD

**Issue by MillennialPirate** [insidesherpa/JPMC-tech-task-1-PY3#53]
My issue is that the server.py is running successfully but I don't think the HTTP server started.
Link for the screenshot is given below. Please do clarify my doubt.

(https://user-images.githubusercontent.com/64896383/81182415-60991680-8fcb-11ea-80f6-09ac1f2a4027.png)

**Comment by Pavan-249** [comment]
Same issue

**Comment by Siddharth20022001** [comment]
Pavan try to fork it...it worked for me.

**Comment by Pavan-249** [comment]
Solved!!try running python server3.py instead of python3 server3.py

**Comment by MillennialPirate** [comment]
Thank you
