### ISSUE TITLE
Issue with Client3.py server

### ISSUE THREAD

**Issue by AGuevara1012** [insidesherpa/JPMC-tech-task-1-PY3#6]
I was able to complete the installation and set-up for the server environment; however, this is the error I encounter when I follow the same steps for the client server. I am working on Python 3.8.0.
![error](https://user-images.githubusercontent.com/55702787/68633878-2554d980-04b9-11ea-98c1-30ce4535bd28.JPG)

**Comment by jbf-insidesherpa** [comment]
@AGuevara1012 you need to have another terminal open where you're running the server application
`python server3.py` before you run the client application

**Comment by AGuevara1012** [comment]
Thanks for your quick response. I attempted again today, while running the server application before running the client, and I had the same error. Here's a screenshot of the windows side by side. 
![error](https://user-images.githubusercontent.com/55702787/68724075-2270ec00-0580-11ea-96f8-3d63992fa291.JPG)

**Comment by jbf-insidesherpa** [comment]
@AGuevara1012 I think you're experiencing a similar problem discussed in this thread:
https://github.com/insidesherpa/JPMC-tech-task-1-PY3/issues/7#issuecomment-554538136

We've discussed the workaround in that situation, can you please try it on your end and let me know if it works for you as well?

Thanks!
