### ISSUE TITLE
Type Error in client3.py file

### ISSUE THREAD

**Issue by tharun143** [insidesherpa/JPMC-tech-task-1-PY3#63]
Traceback (most recent call last):
  File "client3.py", line 52, in <module>
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
![Screenshot from 2020-05-07 17-31-37](https://user-images.githubusercontent.com/41537996/81292123-aa940200-9088-11ea-9588-771e4de823e2.png)
This is the problem I am facing can someone help me out with this?

**Comment by tharun143** [comment]
How I resolved this problem?

Well, I made a prediction that if python3 doesn't work there is a chance that python 2 works. Well, my guess is correct and I ran the server file and client file using python2 and everything went well till now. Closing this issue. Hope you will this comment as helpful

**Comment by shobitgg** [comment]
is there a method to solve it in python 3.5 only ..or is there a method to use both python 3.5 and 2.7 on same machine different time based on priority.I currently have 3.5 and getting same error
