### ISSUE TITLE
OS Error for "python server3.py"

### ISSUE THREAD

**Issue by ankitmpatil** [insidesherpa/JPMC-tech-task-1-PY3#7]
I already had python and git installed in my windows system, yet I installed everything from start to end. But I am getting and OSError as shown in the image while running "python server3.py
![JPM](https://user-images.githubusercontent.com/48452845/68636215-c72ff280-04c8-11ea-8638-5e1a0a5a11d8.PNG)
"

**Comment by jbf-insidesherpa** [comment]
@ankitmpatil you probably have a firewall open preventing you from accessing 8080. You can try the following workarounds:

- temporarily turn off your firewall

- open the `datafeed/server.py` in the repository using your code editor and look for the line where it says `port = 8080`. change that to `port = 8085`
- open the `src/DataStreamer.ts` and change the line where it has `8080` to `8085`

**Comment by YunLu95** [comment]
Hi I'm having similar issue as I run server3.py, it hang there and doesn't continue, I tried change port to 8085 but I couldn't find Datastreamer.ts:
HTTP server started on port 8085
If I interrupt with ctrl-c will return:
^CTraceback (most recent call last):
  File "server3.py", line 320, in <module>
    run(App())
  File "server3.py", line 221, in run
    sleep(1)
KeyboardInterrupt

**Comment by ankitmpatil** [comment]
> @ankitmpatil you probably have a firewall open preventing you from accessing 8080. You can try the following workarounds:
> 
> * temporarily turn off your firewall
> * open the `datafeed/server.py` in the repository using your code editor and look for the line where it says `port = 8080`. change that to `port = 8085`
> * open the `src/DataStreamer.ts` and change the line where it has `8080` to `8085`

Hey,
Thank you so much for your help. My issue got resolved now.
I appreciate your efforts. 
Best, 
Ankit Patil

**Comment by jbf-insidesherpa** [comment]
@YunLu95 sorry, for module 1 there is no DataStreamer.ts.
Instead just change the port in the client3.py (or client.py if you're in the python2.7.x version of the repository)
![image](https://user-images.githubusercontent.com/54832297/69016630-fec40080-09da-11ea-851a-51f9e9fac2a9.png)
