### ISSUE TITLE
Error in opening client3.py

### ISSUE THREAD

**Issue by srivastav-ayush** [insidesherpa/JPMC-tech-task-1-PY3#72]
![SharedScreenshot](https://user-images.githubusercontent.com/51814089/81563794-640a1480-93b4-11ea-90da-f38d7f28daf2.jpg)
I followed all the steps and completed the setup but when I open client3.py I get the above error and when I open the server3.py I get nothing and have to ctrl+C
![Server3](https://user-images.githubusercontent.com/51814089/81564123-e2ff4d00-93b4-11ea-96f1-5ab119695d56.jpg)

**Comment by anikamody** [comment]
I am also getting same error,please tell how to rectify

**Comment by anikettiwariii** [comment]
Did you solve the issue?

**Comment by srivastav-ayush** [comment]
> Did you solve the issue?

No

**Comment by anikettiwariii** [comment]
> No

Oh ok
