### ISSUE TITLE
python3 server3.py python3 client3.py not running

### ISSUE THREAD

**Issue by ishika-a** [insidesherpa/JPMC-tech-task-1-PY3#73]
![image](https://user-images.githubusercontent.com/50668776/81585190-6dee4080-93d1-11ea-9b36-0c1d742e14c8.png)

![image](https://user-images.githubusercontent.com/50668776/81585294-9413e080-93d1-11ea-877b-80d60c268879.png)

even after installing dateutil, python3 server3.py
python3 client3.py
is not running in the way mentioned

**Comment by BSGILL12** [comment]
Exactly I am too facing this error

**Comment by cosmo666** [comment]
try using python server3.py and python client3,py
this worked for me

**Comment by sreyasraj06** [comment]
for me python server3.py worked,but python client3.py is showing some socket errors.

**Comment by JoY-cmd** [comment]
Follow Steps:
1 - Go to CMD
2 - Type: pip -V
3 - You will receive a path, Copy and Paste this location on your folder bar
4 - Find Scripts in it, as I did - C:\Users\YoursID\AppData\Local\Programs\Python\Python38\Scripts 
5 - Go to Edit Environment Variables - System Variables - Path
6 - Paste this location
7- Save everything and rerun the cmd
8 - Use cmd lines: python server3.py and python client3.py

Let me know, If it helps! Cheers!

**Comment by sreyasraj06** [comment]
Actually I got it now,it's because my command prompt with the server.py
which is ported wasn't wasn't open and I then run tht again,then by side I
run the client.py in another prompt.it worked😊

**Comment by devgarg2000** [comment]
After running server3.py it just stuck at that point nothing further is processing

**Comment by AnvitaKn** [comment]
hi, i was doing the JP MORGAN Software Engineering virtual Experience program and even i came across the same error above after which i saw someone say that python server3.py worked so when i typed it in , the command prompt now says : HTTP server started on port 8080. 

I am not able to type the python client3.py , idk what has happened can anyone help me please.
