### ISSUE TITLE
Nothing is happening after python3 server3.py command 

### ISSUE THREAD

**Issue by rath-sidd** [insidesherpa/JPMC-tech-task-1-PY3#74]
I have the same issue as with the #69 issue whose link is there below:
https://github.com/insidesherpa/JPMC-tech-task-1-PY3/issues/69#issue-615251576

**Comment by Rupesh-rkgit** [comment]
use python server3.py command.

**Comment by rath-sidd** [comment]
it's showing no such file for python server3.py
for python3 server3.py it is not showing any error or any result

**Comment by Rupesh-rkgit** [comment]
don't open in administrator prompt.open in other prompt.screenshot of mine system attached.
![Screenshot (65)](https://user-images.githubusercontent.com/57684533/81640777-0f5eac00-943d-11ea-99c0-4be12197e9d8.png)

**Comment by rath-sidd** [comment]
thank you, i get it
