### ISSUE TITLE
Solution to HTTP Server started on port 8080.

### ISSUE THREAD

**Issue by prakharindoria** [insidesherpa/JPMC-tech-task-1-PY3#76]
After you see:
 ****HTTP Server started on port 8080****
Then just open another cmd screen(as administrator) and run the client3.py file also.
You are good to go.
Also If you change the port no. from 8080 to 8085 in server3 file don't forget to change in the client3 file.

**Comment by hfarrell28** [comment]
Hi, I did this and both windows seem to be stuck.

**Comment by prakharindoria** [comment]
Can you share a screenshot of the error?

**Comment by hfarrell28** [comment]
I actually fixed it, but thank you!

**Comment by A-Hazzard** [comment]
> I actually fixed it, but thank you!

How?
