### ISSUE TITLE
'float' object is not subscriptable

### ISSUE THREAD

**Issue by BSGILL12** [insidesherpa/JPMC-tech-task-1-PY3#79]
![Screenshot (264)](https://user-images.githubusercontent.com/47722450/81870648-ea308180-9593-11ea-9056-e06a97247ccd.png)

**Comment by ishika-a** [comment]
it will be prices['ABC'] not price
same for DEF

**Comment by BSGILL12** [comment]
Oh yup silly mistake,.

**Comment by dheerajodha** [comment]
Hi @BSGILL12 since your error has been resolved, can you please close this issue? Thanks!

**Comment by prateekkumbar4546** [comment]
@ishika-a I am getting the same error. Though even if I make it Prices theres one more undefined error

**Comment by ishika-a** [comment]
Can u share with me the screenshot
