### ISSUE TITLE
NOT ABLE TO CREATE A PATCH FILE

### ISSUE THREAD

**Issue by ishika-a** [insidesherpa/JPMC-tech-task-1-PY3#80]
![image](https://user-images.githubusercontent.com/50668776/81873560-a2acf400-9599-11ea-9497-de5563210b9f.png)

pls help coz its saying nothing to commit

**Comment by mihirkemkar** [comment]
Try reloading your window

**Comment by roshniverma21** [comment]
use following commands:-

**git init**
**git add -A**  - try git add instead 
**git config user.email "your_email_address"** - do not use <>
**git config user.name "your_name"** - do not use <>
**git commit -m "Create Patch File"** - double quotes will solve your problem
**git fetch** - to fetch all the branches if your patch is not created in above steps (optional)
**git format-patch -1 HEAD**

your patch is created .check in your local device

_watch this video to understand the concept_ -  https://youtu.be/dTkHmcJsCvM

**Comment by ishika-a** [comment]
![image](https://user-images.githubusercontent.com/50668776/81905304-2985bf00-95e2-11ea-83db-691409ffce0c.png)
![image](https://user-images.githubusercontent.com/50668776/81905336-34d8ea80-95e2-11ea-92ef-7f0f90fc9d2e.png)
![image](https://user-images.githubusercontent.com/50668776/81905364-3bfff880-95e2-11ea-92b8-b17a95b7a5fc.png)
i cant find my patch file . its not showing in local device

**Comment by roshniverma21** [comment]
your patch file is created . 
try to search it in any other folder, refresh or restart your system .
do all the steps i mentioned above once in your command prompt.
