### ISSUE TITLE
Unable to open server3.py in CMD

### ISSUE THREAD

**Issue by nirjs** [insidesherpa/JPMC-tech-task-1-PY3#82]
Unable to open server3.py file in command line. getting an error ( python: can't open file 'server3.py': [Errno 2] No such file or directory ). I have changed the directory also checked for the files. Please help me resolve the issue.

**Comment by dheerajodha** [comment]
Hi @nirjs your error says it can't locate the server3.py inside the directory where you are running this command.

Please make sure you are running this command inside a directory which contains "server3.py" file.

If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!
