### ISSUE TITLE
Client File Error

### ISSUE THREAD

**Issue by Nimish-0** [insidesherpa/JPMC-tech-task-1-PY3#84]
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it.

- tried turning off the firewall.

- and adding a new port 8085 in it.

- no other application has occupied 8085 in my system other than python

- also executed server file in another individual prompt(works perfectly)

still getting the same error again & again.
Please Help
![Screenshot (8)](https://user-images.githubusercontent.com/48803290/81982467-7bb0f980-964f-11ea-9735-c96170135de9.png)

**Comment by abdrehman98** [comment]
I am facing the same issue

**Comment by Cruel-Crab** [comment]
I am too facing the same issue i.e with the client file
![client_fileerror](https://user-images.githubusercontent.com/61859337/82190191-4980ef80-990e-11ea-864e-f70de8e711dd.JPG)
!

**Comment by Surajv311** [comment]
@MohammadHirani @houneie @Nimish-0 
The issue can be resolved by opening and running the server3.py file and client3.py file in two separate terminal windows.
![resolve](https://user-images.githubusercontent.com/59371846/82314607-b0260c00-99e7-11ea-8009-bbe9dee2d7f3.jpg)

**Comment by dheerajodha** [comment]
Hi @Nimish-0 this might help you : https://stackoverflow.com/a/15211481 

If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!

**Comment by Nimish-0** [comment]
@Surajv311 i tried , still with same error

**Comment by dheerajodha** [comment]
Hi @Nimish-0 can you try this ?  https://github.com/insidesherpa/JPMC-tech-task-2/issues/40#issuecomment-619541449

If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!
