### ISSUE TITLE
Issue running python3.py on Windows

### ISSUE THREAD

**Issue by yeryndo** [insidesherpa/JPMC-tech-task-1-PY3#9]
![2019-11-13 (2)](https://user-images.githubusercontent.com/43504775/68786277-7fff4a00-060d-11ea-883b-b2ba70ddbd4a.png)

Using python version 3.7.4 on Windows 10

**Comment by jbf-insidesherpa** [comment]
@yeryndo the command line where you're trying to run the server is in the wrong repository. Notice that it is in **JPMC-tech-task-1** while the other command line where you're running the client is in **JPMC-tech-task-1-py3**. Given that your python version is in python3.7.4, you are supposed to be using **JPMC-tech-task-1-py3** for both server and client apps.
