### ISSUE TITLE
successfully able to run python server3.py but can not be able to run python client3.py

### ISSUE THREAD

**Issue by MThakkar121** [insidesherpa/JPMC-tech-task-1-PY3#93]
![image](https://user-images.githubusercontent.com/36958377/82245327-61815f00-9960-11ea-983f-8172efed421a.png)

@insidesherpa @chandrikadeb7 @Aakash2408

Can you please tell me how to overcome this error ?

**Comment by MThakkar121** [comment]
@Aakash2408

**Comment by Hrithik-Sahni** [comment]
I am having the same doubt my client3.py is not running and server3.p is running

**Comment by SanikaSanaye** [comment]
Hi,

I was having the same error. Turns out my 8080 port was occupied by another service. 

This issue was solved by changing port number to 8085 in both client3.py as well as server3.py files.

Hope this helps.

Happy Coding!

**Comment by MThakkar121** [comment]
> Hi,
> 
> I was having the same error. Turns out my 8080 port was occupied by another service. 
> 
> This issue was solved by changing port number to 8085 in both client3.py as well as server3.py files.
> 
> Hope this helps.
> 
> Happy Coding!

Thanks it successfully work by changing the port numbers !!!😲😅


I forgot that I've installed Oracle 10g which always occupies localport 8080🤦🏻‍♂️

**Comment by SanikaSanaye** [comment]
Glad to help. Do close this issue now that it is resolved.

Good luck with further tasks.

**Comment by MThakkar121** [comment]
Successfully solved..
